Repository GregorLueg/bixverse, pull requests merged in 2025-04, with the labels that each got.

#23 Update README.md
  README.md
Labels: documentation

#25 fix: fixed a spelling mistake in variables that causes issues
  R/graph_methods.R
Labels: bug

#26 fix small bug in verbose and in plan max_workers
  R/graph_methods.R
Labels: bug

#27 Feat/resnik rust
  .gitignore
  NAMESPACE
  R/extendr-wrappers.R
  man/rs_onto_similarity.Rd
  man/rs_onto_similarity_both.Rd
  src/rust/src/fun_helpers.rs
  src/rust/src/fun_hypergeom.rs
  src/rust/src/fun_ica.rs
  src/rust/src/fun_ontology.rs
  src/rust/src/fun_rbh.rs
  src/rust/src/fun_stats.rs
  src/rust/src/helpers_geom_elim.rs
  src/rust/src/helpers_hypergeom.rs
  src/rust/src/helpers_ica.rs
  src/rust/src/helpers_linalg.rs
  src/rust/src/helpers_ontology.rs
  src/rust/src/helpers_rbh.rs
  src/rust/src/lib.rs
  src/rust/src/utils_r_rust.rs
  src/rust/src/utils_rust.rs
  src/rust/src/utils_stats.rs
Labels: enhancement

#34 fix: hypergeom test in rust
  NAMESPACE
  R/GSE_hypergeom.R
  R/extendr-wrappers.R
  inst/tinytest/test_R_rust_equality.R
  man/ontology.Rd
  man/rs_phyper.Rd
  src/rust/src/fun_stats.rs
  src/rust/src/helpers_hypergeom.rs
  tests/tinytest.R
Labels: bug

#37 Fix/gse rust
  R/extendr-wrappers.R
  inst/tinytest/test_hypergeom.R
  src/rust/src/helpers_geom_elim.rs
  src/rust/src/helpers_hypergeom.rs
Labels: bug

#39 Refactor/go elim
  R/GSE_hypergeom.R
  inst/tinytest/test_hypergeom.R
  misc/workbench/tests/rust_in_R.R
  src/rust/src/fun_hypergeom.rs
  src/rust/src/helpers_geom_elim.rs
  src/rust/src/helpers_hypergeom.rs
Labels: enhancement

#45 Fix/housekeeping
  R/extendr-wrappers.R
  docs/change_log.md
  inst/tinytest/test_hypergeom.R
  inst/tinytest/test_set_sims.R
  man/rs_set_similarity_list.Rd
  misc/workbench/tests/rust_in_R.R
  src/rust/Cargo.lock
  src/rust/Cargo.toml
  src/rust/src/fun_hypergeom.rs
  src/rust/src/fun_rbh.rs
  src/rust/src/fun_stats.rs
  src/rust/src/helpers_geom_elim.rs
  src/rust/src/helpers_linalg.rs
  src/rust/src/helpers_rbh.rs
  src/rust/src/utils_r_rust.rs
  src/rust/src/utils_rust.rs
Labels: enhancement

#46 refactor: further borrowing to avoid unnecessary copying
  inst/tinytest/test_onto_similarity.R
  misc/workbench/tests/cPCA.R
  misc/workbench/tests/rust_in_R.R
  src/rust/src/fun_hypergeom.rs
  src/rust/src/fun_rbh.rs
  src/rust/src/fun_stats.rs
  src/rust/src/helpers_geom_elim.rs
  src/rust/src/helpers_ica.rs
  src/rust/src/helpers_linalg.rs
  src/rust/src/helpers_ontology.rs
  src/rust/src/helpers_rbh.rs
  src/rust/src/utils_rust.rs
  src/rust/src/utils_stats.rs
Labels: enhancement
